apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: gpuinfotest
  name: gpuinfotest
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: gpuinfotest
  template:
    metadata:
      labels:
        app: gpuinfotest
    spec:
      # nodeName: node3
      serviceAccountName: gpuinfotest-sa
      containers:
      - image: zxl/gpuinfo:finallll
        name: gpuinfotest
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NVIDIA_VISIBLE_DEVICES
            value: "all"


